// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYbqo4FqJfEuTeLjYid_oBqLTbxE89sjk',
    appId: '1:539030249597:web:c1b2449b130d0854949114',
    messagingSenderId: '539030249597',
    projectId: 'stocker-l-horaire-des-employes',
    authDomain: 'stocker-l-horaire-des-employes.firebaseapp.com',
    storageBucket: 'stocker-l-horaire-des-employes.firebasestorage.app',
    measurementId: 'G-5ZH541ESMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3hTv_BEEACcpVW0qAqEsmql07184_slM',
    appId: '1:539030249597:android:ed2eb5d6fa893152949114',
    messagingSenderId: '539030249597',
    projectId: 'stocker-l-horaire-des-employes',
    storageBucket: 'stocker-l-horaire-des-employes.firebasestorage.app',
  );

}